site_name: Fffffx's Note
site_author: Fffffx
site_description: 可达鸭的笔记本，记录了 ZJU-CS 的一些课程笔记。
repo_url: https://github.com/Fffffx0618/PsyBlog
repo_name: Fffffx

use_directory_urls: false

theme:
  name: material
  language: zh
  html_sanitizer: false
  features:
    - header.autohide
    - content.math
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
    - search.highlight
    - toc.follow

  font:
    text: LXGW WenKai Screen, Microsoft YaHei, sans-serif
    code: JetBrains Mono, Sarasa Mono SC, Consolas, monospace

  icon:
    repo: fontawesome/brands/github
    logo: material/notebook-edit-outline
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: blue-grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Markdown 扩展
markdown_extensions:
  - footnotes
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      inline_syntax: [dollar, round]
      block_syntax: [dollar, square]
      generic: true  # ← 必须为 true！

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.inlinehilite
  - pymdownx.snippets

  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}

plugins:
  - search
  - roamlinks:
      safe_mode: false
      image_embed: true
      image_path: "images"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

extra_css:
  - https://fonts.loli.net/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@300;400;500;600;700&display=swap
  - https://cdn.jsdelivr.net/npm/sarasa-gothic@0.43.0/css/sarasa-mono-sc.css
  - https://cdn.jsdelivr.net/npm/highlight.js@11.9.0/styles/one-dark.min.css
  - stylesheets/blueTopaz.css

  


nav:
  - 首页: 
    - index.md

  - 我的Blog: 
    - blog/index.md
  - 编程语言: 
    - Language/index.md
    - C:
      - Language/C/index.md
      - Language/C/C.md
    - Python:
      - Language/Python/Python.md
  - 程序算法: 
    - Algorithm/index.md
    - 数据结构基础:
      - Algorithm/FDS/index.md
      - Algorithm/FDS/Chap1.md
      - Algorithm/FDS/Chap2.md
      - Algorithm/FDS/Chap3.md
      - Algorithm/FDS/Chap4.md
      - Algorithm/FDS/Chap5.md
      - Algorithm/FDS/Chap6.md
      - Algorithm/FDS/Chap7.md
      - Algorithm/FDS/Chap8.md
      - Algorithm/FDS/Chap9.md
    - 高级数据结构与算法分析:
      - Algorithm/ADS/index.md
      - Algorithm/ADS/Lec1.md
      - Algorithm/ADS/Lec2.md
      - Algorithm/ADS/Lec3.md
      - Algorithm/ADS/Lec4.md
      - Algorithm/ADS/Lec5.md
      - Algorithm/ADS/Lec6.md
      - Algorithm/ADS/Lec7.md
      - Algorithm/ADS/Lec8.md
      - Algorithm/ADS/Lec9.md
      - Algorithm/ADS/Lec10.md
      - Algorithm/ADS/Lec11.md
      - Algorithm/ADS/Lec12.md
      - Algorithm/ADS/Lec13.md
      - Algorithm/ADS/Lec14.md
      - Algorithm/ADS/Lec15.md
  - 体系结构: 
    - System/index.md
    - 计算机组成:
      - System/CO/index.md
      - System/CO/Chapter1.md
      - System/CO/Chapter2.md
      - System/CO/Chapter3.md
      - System/CO/Chapter4.md
      - System/CO/Chapter5.md
      - System/CO/Chapter6.md
  - 数学基础: 
    - Math/index.md
    - 离散数学及其应用:
      - Math/DM/index.md
    - 数值分析:
      - Math/NA/index.md
      - Math/NA/Chap1.md
      - Math/NA/Chap2.md
      - Math/NA/Chap3.md
      - Math/NA/Chap4.md
      - Math/NA/Chap5.md
      - Math/NA/Chap6.md
      - Math/NA/Chap7.md
      - Math/NA/Chap8.md
      - Math/NA/Chap9.md
  - 前后端开发: Develop/index.md

